<script setup lang="ts">
/**
 * pages/dashboard/qrcode.vue — merchant QR code page (Figma screen 05).
 *
 * Shows the QR code encoding the commerce's public review URL, ready to print
 * and put on tables. Protected; the commerce comes from the session.
 */
definePageMeta({ middleware: 'auth' })

interface QrData {
  nom: string
  slug: string
  url: string
  svg: string
}

const { data, error } = await useFetch<QrData>('/api/qrcode')

useSeoMeta({ title: 'Mon QR code · Revu' })

/** Open the print dialog (where the browser also offers "Save as PDF"). */
function imprimer() {
  if (import.meta.client) window.print()
}
</script>

<template>
  <main class="min-h-screen bg-surface pb-12 text-ink">
    <div class="mx-auto max-w-md">
      <!-- HEADER -->
      <header class="bg-white px-5 pb-4 pt-6">
        <NuxtLink to="/dashboard" class="text-sm text-gray-500 transition hover:text-ink">
          ← Tableau de bord
        </NuxtLink>
        <h1 class="mt-2 text-xl font-bold">Mon QR code</h1>
      </header>

      <div class="px-5">
        <p v-if="error" class="mt-8 text-center text-sm text-gray-500">QR code indisponible.</p>

        <template v-else-if="data">
          <p class="mt-2 text-sm text-gray-500">
            Imprimez ce QR code et posez-le sur vos tables ou à la caisse.
          </p>

          <!-- Printable QR card -->
          <div
            id="qr-card"
            class="mt-5 flex flex-col items-center rounded-2xl border border-gray-200 bg-white p-6 text-center"
          >
            <!-- v-html is safe here: the SVG is generated by us, not user input. -->
            <div class="qr-svg w-48" v-html="data.svg" />
            <p class="mt-4 font-bold">{{ data.nom }}</p>
            <p class="text-xs text-gray-500">Scannez pour donner votre avis</p>
            <p class="mt-1 break-all text-xs text-brand">{{ data.url }}</p>
          </div>

          <button
            type="button"
            class="mt-5 w-full rounded-xl bg-brand py-3.5 font-semibold text-white transition hover:bg-brand-dark active:scale-[0.98]"
            @click="imprimer"
          >
            Imprimer / Enregistrer en PDF
          </button>

          <p class="mt-4 text-xs text-gray-500">
            💡 Conseil : placez le QR code sur chaque table pour maximiser les réponses.
          </p>
        </template>
      </div>
    </div>
  </main>
</template>

<style>
/* Make the inline QR SVG fill its sized wrapper. */
.qr-svg svg {
  display: block;
  width: 100%;
  height: auto;
}

/* When printing, show only the QR card. */
@media print {
  body * {
    visibility: hidden;
  }
  #qr-card,
  #qr-card * {
    visibility: visible;
  }
  #qr-card {
    position: absolute;
    inset: 0;
    margin: auto;
    border: none;
  }
}
</style>
